### ISSUE TITLE
Pls

### ISSUE THREAD

**Issue by SqdGoodlol** [WolfyScript/CustomCrafting-Wiki#16]
Please add to make @a @p work for the issue of items. For example / customcrafting give @p item:item1

**Comment by WolfyScript** [comment]
Please use the "Feature request" preset and follow it next time! This includes a concise title, that describes the request. 
A title just called "Pls" is not going to be taken seriously and if I see the title I don't know what the issue is about! 

I will keep this issue open for now and see if I can implement the request somehow.

Any future issues with such a title will be closed without any further notice!
