### ISSUE TITLE
ItemsAdder - Removing meta from items

### ISSUE THREAD

**Issue by SignorPollito** [WolfyScript/CustomCrafting-Wiki#56]
**Describe the bug**
When an ItemsAdder item with modified meta (name or lore, etc.) is put in a CustomCrafting GUI (example: when creating a custom recipe), the meta disappears.

**To Reproduce**
1. Create an item using ItemsAdder
2. Modify its meta with a plugin
3. Put the item in a CustomCrafting GUI
4. The meta will disappear

**Expected behavior**
The meta should not disappear when putting an itemsadder item

**Video**
https://imgur.com/a/LpBgmg9

**Server (please complete the following information):**
 - Server Software: Purpur
 - Minecraft version: 1.16.5
 - Java version: 16

**Additional context**
Thank you for all your huge work on this plugin and on resolving problems/adding compatilibities with other plugins!

**Comment by WolfyScript** [comment]
This is intended as WolfyUtilities creates a reference to the saved item from ItemsAdder. This synchronises the ItemsAdder items with your recipes, so if you change the item in ItemsAdder they are updated automatically in the recipes.
Plus, this improves the performance of the recipe check, because it only has to check if the items contain the ItemsAdder id.
I recommend to edit the items in ItemsAdder itself.

If you still wanna disable this behavior you can do that in the `WolfyUtilities/config.yml`.
Downsides:
- Worse performance, especially when server has lot's of recipes. 
- No item sync.

You could bypass these downsides by saving the edited item via the ItemCreator and use the items from `/cc give`, but that's an extra step.

**Comment by SignorPollito** [comment]
Thank you, solved my problem!
Closing this as it's not a bug.
