### ISSUE TITLE
Errors on startup

### ISSUE THREAD

**Issue by Exatoon27** [WolfyScript/CustomCrafting-Wiki#84]
When starting the server, I get these errors in the console

![imagen](https://user-images.githubusercontent.com/73707496/163699145-6ee066cb-e473-467d-9a47-1c5af827a538.png)
![imagen](https://user-images.githubusercontent.com/73707496/163699153-5bb1ea40-52be-4dbe-bc56-0736dc5c121b.png)
![imagen](https://user-images.githubusercontent.com/73707496/163699169-b50e5efb-af97-43ef-9237-7fd1e732bb7d.png)
![imagen](https://user-images.githubusercontent.com/73707496/163699175-1bdafc1b-3309-401e-9e4c-eb3a877ddd62.png)
![imagen](https://user-images.githubusercontent.com/73707496/163699190-07f79525-d15e-491f-8778-8873692c0486.png)

I run a server with Java 16, PaperMC 1.16.5, and I have plugins versions customcrafting-spigot-2.16.6.0-f.jar and wolfyutilities-3.16.2.0.jar

**Comment by WolfyScript** [comment]
That is happening because you use an old version of CustomCrafting and a more recent version of WolfyUtilities.
You should update CustomCrafting to 3.16.3.3 ([CurseForge](https://www.curseforge.com/minecraft/bukkit-plugins/customcrafting-advanced-custom-recipes/files)) and WolfyUtilities 4.16.1.0 ([GitHub](https://github.com/WolfyScript/WolfyUtils-Spigot/releases/tag/v4.16.1.0))

**Comment by Exatoon27** [comment]
I already updated them, but it tells me this
![imagen](https://user-images.githubusercontent.com/73707496/163723268-5a938e32-baa5-43a4-b298-2786ea8579f2.png)
