### ISSUE TITLE
Version 1.6.5.1.3 Mass flood console warning (A HUGE amount) 

### ISSUE THREAD

**Issue by EchocallingEarth** [WolfyScript/CustomCrafting-Wiki#9]
Full console log - a rather large log caused by the repeating spamming warnings

https://paste.enginehub.org/0In6ieD9D

Additional information:
Paper 1.16.5

Further information upon request

**Comment by WolfyScript** [comment]
It looks like that CustomCrafting has no permission to write to those recipe/item files.
Because of that, it prints an error for each file it doesn't has permission
For example this file: plugins/CustomCrafting/data/armor/items/guard_helmet.json (Permission denied)

**Comment by WolfyScript** [comment]
It often happens when you copy files, which belong to another user and/or have invalid permissions.
https://www.spigotmc.org/threads/permission-denied.332534/
https://www.spigotmc.org/threads/severe-java-io-filenotfoundexception-world-level-dat_new-permission-denied.49080/

If you use a server host it might be an error on their side.

**Comment by EchocallingEarth** [comment]
Thank you, How I failed to set perms is beyond me as i usually always run chown and make sure after updating. Silly me and thanks. I'll close this issue which much appreciation too you for see what I missed.
